name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      release_notes:
        description: "Release notes (optional)"
        required: false
        default: ""

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    # Only allow repository owner or collaborators
    if: github.actor == github.repository_owner || contains(fromJSON('["ChristianANoeddeboe"]'), github.actor)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Test CLI functionality
        run: |
          poetry run newt --help
          poetry run newt -v

      - name: Get current version
        id: current_version
        run: |
          CURRENT=$(poetry version -s)
          echo "current=$CURRENT" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump_version
        run: |
          poetry version ${{ github.event.inputs.version_bump }}
          NEW_VERSION=$(poetry version -s)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Bumped version from ${{ steps.current_version.outputs.current }} to $NEW_VERSION"

      - name: Build and test package
        run: |
          poetry build
          poetry run newt -v

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump version to ${{ steps.bump_version.outputs.new_version }}"
          title: "🚀 Release v${{ steps.bump_version.outputs.new_version }}"
          body: |
            ## Release v${{ steps.bump_version.outputs.new_version }}
            
            This PR prepares a new release by bumping the version from `${{ steps.current_version.outputs.current }}` to `${{ steps.bump_version.outputs.new_version }}`.
            
            ### Changes
            - Version bump (${{ github.event.inputs.version_bump }}): `${{ steps.current_version.outputs.current }}` → `${{ steps.bump_version.outputs.new_version }}`
            - Package builds successfully
            - CLI functionality tested
            
            ### Release Notes
            ${{ github.event.inputs.release_notes || 'No additional release notes provided.' }}
            
            ### Next Steps
            1. Review and merge this PR
            2. Create a release from the tag `v${{ steps.bump_version.outputs.new_version }}`
            3. The build workflow will automatically attach assets to the release
            
            ---
            *This PR was automatically created by the Release workflow.*
          branch: release/v${{ steps.bump_version.outputs.new_version }}
          delete-branch: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-v${{ steps.bump_version.outputs.new_version }}
          path: dist/